name: "Listar Buckets S3"

on:
  workflow_dispatch:  # Permite disparo manual ou via API

jobs:
  listar-buckets:
    runs-on: ubuntu-latest

    steps:
    - name: "Configurar AWS CLI"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: "📋 Listar Buckets S3"
      run: aws s3 ls
